const signs = [
  {
    URL: './images/A_lot.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'A lot',
  },
  {
    URL: './images/Abandon.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Abandon',
  },
  {
    URL: './images/Abortion.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Abortion',
  },
  {
    URL: './images/Addicted.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Addicted',
  },
  {
    URL: './images/Advise.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Advise',
  },
  {
    URL: './images/Africa.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Africa',
  },
  {
    URL: './images/Alcohol.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Alcohol',
  },
  {
    URL: './images/All_night.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'All night',
  },
  {
    URL: './images/Alone.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Alone',
  },
  {
    URL: './images/Announce.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Announce',
  },
  {
    URL: './images/Answer.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Answer',
  },
  {
    URL: './images/Applause.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Applause',
  },
  {
    URL: './images/Apple.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Apple',
  },
  {
    URL: './images/Appointment.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Appointment',
  },
  {
    URL: './images/Association.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Association',
  },
  {
    URL: './images/Australia.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Australia',
  },
  {
    URL: './images/Authority.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Authority',
  },
  {
    URL: './images/Awful.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Awful',
  },
  {
    URL: './images/Bad.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Bad',
  },
  {
    URL: './images/Ball.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Ball',
  },
  {
    URL: './images/Balloon.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Balloon',
  },
  {
    URL: './images/Beard.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Beard',
  },
  {
    URL: './images/Beautiful.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Beautiful',
  },
  {
    URL: './images/Become.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Become',
  },
  {
    URL: './images/Bee.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Bee',
  },
  {
    URL: './images/Book.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Book',
  },
  {
    URL: './images/Boy.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Boy',
  },
  {
    URL: './images/Bread.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Bread',
  },
  {
    URL: './images/Breathe.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Breathe',
  },
  {
    URL: './images/Bridge.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Bridge',
  },
  {
    URL: './images/Business.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Business',
  },
  {
    URL: './images/But.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'But',
  },
  {
    URL: './images/Cafeteria.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Cafeteria',
  },
  {
    URL: './images/Cat.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Cat',
  },
  {
    URL: './images/Cereal.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Cereal',
  },
  {
    URL: './images/Character.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Character',
  },
  {
    URL: './images/Checkers.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Checkers',
  },
  {
    URL: './images/Checking-account.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Checking account',
  },
  {
    URL: './images/Chicago.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Chicago',
  },
  {
    URL: './images/Choke.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Choke',
  },

  {
    URL: './images/Christmas.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Christmas',
  },
  {
    URL: './images/Cigarette.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Cigarette',
  },
  {
    URL: './images/Close_window.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Close window',
  },
  {
    URL: './images/Close.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Close',
  },
  {
    URL: './images/Coffee.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Coffee',
  },
  {
    URL: './images/Coins.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Coins',
  },
  {
    URL: './images/Collect.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Collect',
  },
  {
    URL: './images/Color.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Color',
  },
  {
    URL: './images/Computer.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Computer',
  },
  {
    URL: './images/Conflict.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Conflict',
  },
  {
    URL: './images/Contact.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Contact',
  },
  {
    URL: './images/Cook.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Cook',
  },
  {
    URL: './images/Cooking.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Cooking',
  },
  {
    URL: './images/Cooperate.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Cooperate',
  },
  {
    URL: './images/Country.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Country',
  },
  {
    URL: './images/Cousin.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Cousin',
  },
  {
    URL: './images/Cow.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Cow',
  },
  {
    URL: './images/Crazy.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Crazy',
  },
  {
    URL: './images/Cry.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Cry',
  },
  {
    URL: './images/Curly.gif',
    hands: 'Ek',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Curly',
  },

  {
    URL: './images/Dance.gif',
    hands: 'Dho',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Dance',
  },
  {
    URL: './images/Dim.gif',
    hands: 'Dho',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Dim',
  },
  {
    URL: './images/Dirty.gif',
    hands: 'Dho',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Dirty',
  },
  {
    URL: './images/Disappear.gif',
    hands: 'Dho',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Disappear',
  },
  {
    URL: './images/Distribute.gif',
    hands: 'Dho',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Distribute',
  },
  {
    URL: './images/Drink.gif',
    hands: 'Dho',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Drink',
  },
  {
    URL: './images/Drunk.gif',
    hands: 'Dho',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Drunk',
  },
  {
    URL: './images/During.gif',
    hands: 'Dho',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'During',
  },
  {
    URL: './images/Dye.gif',
    hands: 'Dho',
    handshape: 'A',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Dye',
  },
  {
    URL: './images/E-mail.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Email',
  },
  {
    URL: './images/Earth.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Earth',
  },
  {
    URL: './images/Eat.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Eat',
  },
  {
    URL: './images/Egypt.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Egypt',
  },
  {
    URL: './images/Either.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Either',
  },
  {
    URL: './images/Empty.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Empty',
  },
  {
    URL: './images/Encyclopedia.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Encyclopedia',
  },
  {
    URL: './images/Episcopal.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Episcopal',
  },
  {
    URL: './images/Everyday.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Everyday',
  },
  {
    URL: './images/Excited.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Excited',
  },
  {
    URL: './images/Experience.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Experience',
  },
  {
    URL: './images/Express.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Express',
  },
  {
    URL: './images/Family.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Family',
  },
  {
    URL: './images/Famous.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Famous',
  },
  {
    URL: './images/Fancy.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Fancy',
  },
  {
    URL: './images/Farm.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Farm',
  },
  {
    URL: './images/Feedback.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Feedback',
  },
  {
    URL: './images/Fight.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Fight',
  },
  {
    URL: './images/Finally.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Finally',
  },
  {
    URL: './images/Fine.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Fine',
  },
  {
    URL: './images/Fingerspell.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Fingerspell',
  },
  {
    URL: './images/Flashlight.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Flashlight',
  },
  {
    URL: './images/Flat.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Flat',
  },
  {
    URL: './images/Focus.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Focus',
  },
  {
    URL: './images/Football.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Football',
  },
  {
    URL: './images/Force.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Force',
  },
  {
    URL: './images/Foreign.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Foreign',
  },
  {
    URL: './images/Fork.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Fork',
  },
  {
    URL: './images/Formerly.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Formerly',
  },
  {
    URL: './images/Free.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Free',
  },
  {
    URL: './images/Freeze.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Freeze',
  },
  {
    URL: './images/Friendly.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Friendly',
  },
  {
    URL: './images/From-now-on.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'From now on',
  },
  {
    URL: './images/Funeral.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Okati',
    location: 'Uno',
    movement: 'Onru',
    name: 'Funeral',
  },
  {
    URL: './images/General.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Rendu',
    location: 'Uno',
    movement: 'Onru',
    name: 'General',
  },
  {
    URL: './images/Get.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Rendu',
    location: 'Uno',
    movement: 'Onru',
    name: 'Get',
  },
  {
    URL: './images/Giraffe.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Rendu',
    location: 'Uno',
    movement: 'Onru',
    name: 'Giraffe',
  },
  {
    URL: './images/Girl.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Rendu',
    location: 'Uno',
    movement: 'Onru',
    name: 'Girl',
  },
  {
    URL: './images/Glasses.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Rendu',
    location: 'Uno',
    movement: 'Onru',
    name: 'Glasses',
  },
  {
    URL: './images/Globe.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Rendu',
    location: 'Uno',
    movement: 'Onru',
    name: 'Globe',
  },
  {
    URL: './images/Go.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Rendu',
    location: 'Uno',
    movement: 'Onru',
    name: 'Go',
  },
  {
    URL: './images/Good_luck.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Rendu',
    location: 'Uno',
    movement: 'Onru',
    name: 'Good luck',
  },
  {
    URL: './images/Good.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Rendu',
    location: 'Uno',
    movement: 'Onru',
    name: 'Good',
  },
  {
    URL: './images/Grammar.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Rendu',
    location: 'Uno',
    movement: 'Onru',
    name: 'Grammar',
  },
  {
    URL: './images/Grandfather.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Rendu',
    location: 'Uno',
    movement: 'Onru',
    name: 'Grandfather',
  },
  {
    URL: './images/Grandmother.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Rendu',
    location: 'Uno',
    movement: 'Onru',
    name: 'Grandmother',
  },
  {
    URL: './images/Greece.gif',
    hands: 'Dho',
    handshape: 'B',
    'Palm Orientation': 'Rendu',
    location: 'Uno',
    movement: 'Onru',
    name: 'Greece',
  },
  {
    URL: './images/Hair.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Uno',
    movement: 'Onru',
    name: 'Hair',
  },
  {
    URL: './images/Happen.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Uno',
    movement: 'Onru',
    name: 'Happen',
  },
  {
    URL: './images/Hard.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Uno',
    movement: 'Onru',
    name: 'Hard',
  },
  {
    URL: './images/Hate.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Uno',
    movement: 'Onru',
    name: 'Hate',
  },

  {
    URL: './images/Headache.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Uno',
    movement: 'Onru',
    name: 'Headache',
  },
  {
    URL: './images/Hurricane.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Uno',
    movement: 'Onru',
    name: 'Hurricane',
  },
  {
    URL: './images/Hurt.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Uno',
    movement: 'Onru',
    name: 'Hurt',
  },
  {
    URL: './images/Ignition_off.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Ignition off',
  },
  {
    URL: './images/Ignore.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Ignore',
  },
  {
    URL: './images/Important.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Important',
  },
  {
    URL: './images/Impossible.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Impossible',
  },
  {
    URL: './images/Include.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Include',
  },
  {
    URL: './images/Intercourse.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Intercourse',
  },
  {
    URL: './images/Internet.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Internet',
  },
  {
    URL: './images/Interpret.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Interpret',
  },
  {
    URL: './images/Introduce.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Introduce',
  },
  {
    URL: './images/Island.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Island',
  },
  {
    URL: './images/Jesus.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Jesus',
  },
  {
    URL: './images/Jewish.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Jewish',
  },
  {
    URL: './images/Kid.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Kid',
  },
  {
    URL: './images/Kiss.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Kiss',
  },
  {
    URL: './images/Kitchen.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Kitchen',
  },
  {
    URL: './images/Know.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Know',
  },
  {
    URL: './images/Laugh.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Laugh',
  },
  {
    URL: './images/Learn.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Learn',
  },
  {
    URL: './images/Light-match.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Light match',
  },
  {
    URL: './images/Line.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Line',
  },
  {
    URL: './images/Look.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Look',
  },
  {
    URL: './images/Lose-weight.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Lose weight',
  },
  {
    URL: './images/Make.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Make',
  },
  {
    URL: './images/Marry.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Marry',
  },
  {
    URL: './images/Match.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Match',
  },
  {
    URL: './images/Melon.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Melon',
  },
  {
    URL: './images/Member.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Member',
  },
  {
    URL: './images/Merge.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Merge',
  },
  {
    URL: './images/Messed-up.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Messed up',
  },
  {
    URL: './images/Milk.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Milk',
  },
  {
    URL: './images/Misunderstand.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Misunderstand',
  },
  {
    URL: './images/Mix-up.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Mix up',
  },
  {
    URL: './images/More.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'More',
  },
  {
    URL: './images/Mosquito.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Mosquito',
  },
  {
    URL: './images/Mustache.gif',
    hands: 'Dho',
    handshape: 'C',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Mustache',
  },
  {
    URL: './images/Nervous.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Nervous',
  },
  {
    URL: './images/Nigeria.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Nigeria',
  },
  {
    URL: './images/None.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'None',
  },
  {
    URL: './images/Nose.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Rendu',
    location: 'Tres',
    movement: 'Onru',
    name: 'Nose',
  },
  {
    URL: './images/Octopus.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Rendu',
    location: 'Dos',
    movement: 'Onru',
    name: 'Octopus',
  },
  {
    URL: './images/Old.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Rendu',
    location: 'Dos',
    movement: 'Onru',
    name: 'Old',
  },
  {
    URL: './images/Olympics.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Rendu',
    location: 'Dos',
    movement: 'Onru',
    name: 'Olympics',
  },
  {
    URL: './images/Orange.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Rendu',
    location: 'Dos',
    movement: 'Onru',
    name: 'Orange',
  },
  {
    URL: './images/Orthodox.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Rendu',
    location: 'Dos',
    movement: 'Onru',
    name: 'Orthodox',
  },
  {
    URL: './images/Owl.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Rendu',
    location: 'Dos',
    movement: 'Onru',
    name: 'Owl',
  },
  {
    URL: './images/Pancake.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Onru',
    name: 'Pancake',
  },
  {
    URL: './images/Paper.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Onru',
    name: 'Paper',
  },
  {
    URL: './images/Parallel.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Onru',
    name: 'Parallel',
  },
  {
    URL: './images/Pay-attention.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Onru',
    name: 'Pay attention',
  },
  {
    URL: './images/Pea-brain.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Onru',
    name: 'Pea brain',
  },
  {
    URL: './images/Penis.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Onru',
    name: 'Penis',
  },
  {
    URL: './images/People_audience.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Onru',
    name: 'People audience',
  },
  {
    URL: './images/Picture.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Onru',
    name: 'Picture',
  },
  {
    URL: './images/Pig.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Onru',
    name: 'Pig',
  },
  {
    URL: './images/Pillow.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Onru',
    name: 'Pillow',
  },
  {
    URL: './images/Play_around.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Onru',
    name: 'Play around',
  },
  {
    URL: './images/Play.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Onru',
    name: 'Play',
  },
  {
    URL: './images/Polite.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Onru',
    name: 'Polite',
  },
  {
    URL: './images/Poor.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Onru',
    name: 'Poor',
  },
  {
    URL: './images/Postpone.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Onru',
    name: 'Postpone',
  },
  {
    URL: './images/Potato.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Onru',
    name: 'Potato',
  },
  {
    URL: './images/Predict.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Onru',
    name: 'Predict',
  },
  {
    URL: './images/Pregnant.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Onru',
    name: 'Pregnant',
  },
  {
    URL: './images/Priest.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Onru',
    name: 'Priest',
  },
  {
    URL: './images/Puerto_Rico.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Onru',
    name: 'Puerto Rico',
  },
  {
    URL: './images/Puff-smoke.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Onru',
    name: 'Puff smoke',
  },
  {
    URL: './images/Raccoon.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Raccoon',
  },
  {
    URL: './images/Race.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Race',
  },
  {
    URL: './images/Radio.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Radio',
  },
  {
    URL: './images/Rainbow.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Rainbow',
  },
  {
    URL: './images/Rat.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Rat',
  },
  {
    URL: './images/Read.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Read',
  },
  {
    URL: './images/Really.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Really',
  },
  {
    URL: './images/Reduce.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Reduce',
  },
  {
    URL: './images/Replace.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Replace',
  },
  {
    URL: './images/Responsibility.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Responsibility',
  },
  {
    URL: './images/Ride.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Ride',
  },

  {
    URL: './images/Road.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Road',
  },
  {
    URL: './images/Roommate.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Roommate',
  },
  {
    URL: './images/Ruin.gif',
    hands: 'Dho',
    handshape: 'D',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Ruin',
  },
  {
    URL: './images/Salt.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Salt',
  },
  {
    URL: './images/San_Francisco.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'San Francisco',
  },
  {
    URL: './images/Sarcasm.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Sarcasm',
  },
  {
    URL: './images/Save-money.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Save money',
  },
  {
    URL: './images/School.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'School',
  },
  {
    URL: './images/Scotland.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Scotland',
  },
  {
    URL: './images/Secret.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Secret',
  },
  {
    URL: './images/See_saw.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'See saw',
  },
  {
    URL: './images/Sentence.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Sentence',
  },
  {
    URL: './images/Sew.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Sew',
  },
  {
    URL: './images/Shave.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Shave',
  },
  {
    URL: './images/Shoes.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Shoes',
  },
  {
    URL: './images/Sick.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Sick',
  },
  {
    URL: './images/Silly.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Silly',
  },
  {
    URL: './images/Simple.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Simple',
  },
  {
    URL: './images/Sit.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Sit',
  },
  {
    URL: './images/Smile.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Smile',
  },
  {
    URL: './images/Socks.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Socks',
  },
  {
    URL: './images/Speech.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Speech',
  },
  {
    URL: './images/Spread.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Spread',
  },
  {
    URL: './images/Square.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Square',
  },
  {
    URL: './images/Stay.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Stay',
  },
  {
    URL: './images/Steal.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Steal',
  },
  {
    URL: './images/Steam.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Steam',
  },
  {
    URL: './images/Stimulate.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Stimulate',
  },
  {
    URL: './images/Storm.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Storm',
  },
  {
    URL: './images/Strict.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Strict',
  },
  {
    URL: './images/Struggle.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Struggle',
  },
  {
    URL: './images/Stuck.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Stuck',
  },
  {
    URL: './images/Stuck.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Stuck',
  },
  {
    URL: './images/Stupid.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Stupid',
  },
  {
    URL: './images/Subway.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Subway',
  },
  {
    URL: './images/Summer.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Summer',
  },
  {
    URL: './images/Swear.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Swear',
  },
  {
    URL: './images/Sweden.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Sweden',
  },
  {
    URL: './images/Swing.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Swing',
  },
  {
    URL: './images/System.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'System',
  },

  {
    URL: './images/Take_break.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Take break',
  },
  {
    URL: './images/Talk-to-self.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Talk to self',
  },
  {
    URL: './images/Tall.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Tall',
  },
  {
    URL: './images/Tan.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Tan',
  },
  {
    URL: './images/Tape.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Tape',
  },
  {
    URL: './images/Temple.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Temple',
  },
  {
    URL: './images/Tend.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Tend',
  },
  {
    URL: './images/Thank_you.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Thank you',
  },
  {
    URL: './images/Thief.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Thief',
  },
  {
    URL: './images/Thin.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Thin',
  },
  {
    URL: './images/Think_opposite.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Think opposite',
  },
  {
    URL: './images/Thursday.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Thursday',
  },
  {
    URL: './images/Tie.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Tie',
  },
  {
    URL: './images/Tiny.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Tiny',
  },
  {
    URL: './images/To-fool.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'To-fool',
  },
  {
    URL: './images/Toast.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Toast',
  },
  {
    URL: './images/Touch-heart.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Touch heart',
  },
  {
    URL: './images/Train.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Train',
  },
  {
    URL: './images/Trim_hedge.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Trim hedge',
  },
  {
    URL: './images/Triple.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Triple',
  },
  {
    URL: './images/Trouble.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Trouble',
  },
  {
    URL: './images/Trumpet.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Trumpet',
  },
  {
    URL: './images/Try.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Try',
  },
  {
    URL: './images/Twice.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Moodu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Twice',
  },
  {
    URL: './images/Ugly.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Naalugu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Ugly',
  },
  {
    URL: './images/Uniform.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Naalugu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Uniform',
  },
  {
    URL: './images/Very.gif',
    hands: 'Dho',
    handshape: 'E',
    'Palm Orientation': 'Naalugu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Very',
  },
  {
    URL: './images/Vote.gif',
    hands: 'Dho',
    handshape: 'F',
    'Palm Orientation': 'Naalugu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Vote',
  },
  {
    URL: './images/Wag.gif',
    hands: 'Dho',
    handshape: 'F',
    'Palm Orientation': 'Naalugu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Wag',
  },
  {
    URL: './images/Waist.gif',
    hands: 'Dho',
    handshape: 'F',
    'Palm Orientation': 'Naalugu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Waist',
  },
  {
    URL: './images/Walk.gif',
    hands: 'Dho',
    handshape: 'F',
    'Palm Orientation': 'Naalugu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Walk',
  },
  {
    URL: './images/Want.gif',
    hands: 'Dho',
    handshape: 'F',
    'Palm Orientation': 'Naalugu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Want',
  },
  {
    URL: './images/Want.gif',
    hands: 'Dho',
    handshape: 'F',
    'Palm Orientation': 'Naalugu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Want',
  },
  {
    URL: './images/Watch.gif',
    hands: 'Dho',
    handshape: 'F',
    'Palm Orientation': 'Naalugu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Watch',
  },
  {
    URL: './images/Water.gif',
    hands: 'Dho',
    handshape: 'F',
    'Palm Orientation': 'Naalugu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Water',
  },
  {
    URL: './images/Whale.gif',
    hands: 'Dho',
    handshape: 'F',
    'Palm Orientation': 'Naalugu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Whale',
  },
  {
    URL: './images/What.gif',
    hands: 'Dho',
    handshape: 'F',
    'Palm Orientation': 'Naalugu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'What',
  },
  {
    URL: './images/Wheel.gif',
    hands: 'Dho',
    handshape: 'F',
    'Palm Orientation': 'Naalugu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Wheel',
  },
  {
    URL: './images/Wheelchair.gif',
    hands: 'Dho',
    handshape: 'F',
    'Palm Orientation': 'Naalugu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Wheelchair',
  },
  {
    URL: './images/Who.gif',
    hands: 'Dho',
    handshape: 'F',
    'Palm Orientation': 'Naalugu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Who',
  },

  {
    URL: './images/Why.gif',
    hands: 'Dho',
    handshape: 'F',
    'Palm Orientation': 'Naalugu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Why',
  },
  {
    URL: './images/Wide.gif',
    hands: 'Dho',
    handshape: 'F',
    'Palm Orientation': 'Naalugu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Wide',
  },
  {
    URL: './images/Wolf.gif',
    hands: 'Dho',
    handshape: 'F',
    'Palm Orientation': 'Naalugu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Wolf',
  },
  {
    URL: './images/Work.gif',
    hands: 'Dho',
    handshape: 'F',
    'Palm Orientation': 'Naalugu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Work',
  },
  {
    URL: './images/Write.gif',
    hands: 'Dho',
    handshape: 'F',
    'Palm Orientation': 'Naalugu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Write',
  },
  {
    URL: './images/Wrong.gif',
    hands: 'Dho',
    handshape: 'F',
    'Palm Orientation': 'Naalugu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Wrong',
  },
  {
    URL: './images/Yawn.gif',
    hands: 'Dho',
    handshape: 'F',
    'Palm Orientation': 'Naalugu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Yawn',
  },
  {
    URL: './images/Yellow.gif',
    hands: 'Dho',
    handshape: 'F',
    'Palm Orientation': 'Naalugu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Yellow',
  },
  {
    URL: './images/Yesterday.gif',
    hands: 'Dho',
    handshape: 'F',
    'Palm Orientation': 'Naalugu',
    location: 'Dos',
    movement: 'Irandu',
    name: 'Yesterday',
  },
]

const STIMULI_SIGNS = [
  'AUSTRALIA',
  'BRIDGE',
  'CHARACTER',
  'CHICAGO',
  'CIGARETTE',
  'COW',
  'CURLY',
  'DIRTY',
  'DYE',
  'FAMOUS',
  'FANCY',
  'FOCUS',
  'FORK',
  'FREE',
  'FUNERAL',
  'GIRAFFE',
  'INTERNET',
  'JESUS',
  'MIX-UP',
  'OLYMPICS',
  'PIG',
  'PUFF-SMOKE',
  'RAINBOW',
  'SALT',
  'SAVE-MONEY',
  'SCOTLAND',
  'SENTENCE',
  'SILLY',
  'STRUGGLE',
  'SUBWAY',
  'TEND',
  'WHEEL',
  'YAWN',
]
const POSITION_RANGE = [2, 7, 13, 18, 23]

let filterReadySigns = {}

signs.forEach((sign) => {
  filterReadySigns[sign.name] = sign
})

const sign_names = JSON.parse(localStorage.getItem('signs'))
let initialSigns = []

if (sign_names) {
  initialSigns = sign_names.map((name) => {
    if (filterReadySigns[name]) {
      return filterReadySigns[name]
    }
    return null
  })
}

/* filter logic */
let results = []
let filters = {}

function addSign(sign, index) {
  const id = sign.name
  $('.results-grid').append(
    `<div class="result-box" id="${index}">
    <div class="result-image" id="${id}">
    </div>
    <div class="result-title">
    <p><strong>${sign.name}</strong></p>
    </div>
    <div class="sign-properties">
    <p><strong>Hands:</strong> ${sign.hands}</p>
    <span class="seperator">|</span>
    <p><strong>Handshape:</strong> ${sign.handshape}</p>
    <span class="seperator">|</span>
    <p><strong>Palm Orientation:</strong> ${sign['Palm Orientation']}</p>
    <span class="seperator">|</span>
    <p><strong>Location:</strong> ${sign.location}</p>
    <span class="seperator">|</span>
    <p><strong>Movement:</strong> ${sign.movement}</p>
    </div>
    </div>`
  )
  let curr = document.getElementById(`${id}`)
  curr.style.backgroundImage = `url(.${sign.URL})`
}

function addInitialSign(name) {
  const id = name.split(' ').join('_')
  $('.results-grid').append(
    `<div class="result-box"> <div class="result-image" id="${id}"></div><div class="result-title"><p> ${name} </p></div></div>`
  )
  let curr = document.getElementById(`${id}`)
  curr.style.backgroundImage = `url(../images/${id}.gif)`
}

function loadSigns() {
  signs.forEach((sign) => addSign(sign))
}

function updateResults(sign) {
  if (!results.includes(sign)) {
    results.push(sign)
  }
}

function signExist(signName) {
  const localSigns = JSON.parse(localStorage.getItem('signs'))
  const results = localSigns.filter((sign) => sign.name === signName)
  return results.length > 0
}

const filterContainers = [
  'movement-filters',
  'location-filters',
  'hands-filters',
]

/**
 * check if the filter exist and sign value match the filter's value
 * @param {String} type (filter type)
 * @param {Object} sign
 */
function isFilterMatch(type, sign) {
  return filters[type] && filters[type].includes(sign[type])
}

function hideFilterContainer(containerId) {
  const filtersEl = document.getElementById(containerId)
  filtersEl.style.display = 'none'
}

function toggleFilters(containerId) {
  const filtersEl = document.getElementById(containerId)
  const clearEl = document.getElementById('clear')

  // hide other filter containers and toggle only the filter container with the containerId
  filterContainers
    .filter((id) => id !== containerId)
    .forEach((id) => hideFilterContainer(id))

  // toggle the display property of the filter-container
  filtersEl.style.display = `${
    filtersEl.style.display === 'none' || filtersEl.style.display === ''
      ? 'flex'
      : 'none'
  }`
  // toggle display of clear all button based on the display of filter-container
  clearEl.style.display = `${
    filtersEl.style.display === 'flex' ? 'block' : 'none'
  }`
}

/** clear all filters */
function clearFilters() {
  filters = []
  const filterElements = document.querySelectorAll('.filter-column p')
  filterElements.forEach((element) => (element.style.fontWeight = 'normal'))
  filterContainers.forEach((containerId) => hideFilterContainer(containerId))
  // hide clear all button
  const clearEl = document.getElementById('clear')
  clearEl.style.display = 'none'
  // signs container
  // remove all child nodes of signs container
  $('.results-grid')[0].innerHTML = ''
  const localSigns = JSON.parse(localStorage.getItem('signs'))
  localSigns.forEach((sign) => addInitialSign(sign))
  // update the number of signs in the UI
  $('.number-of-signs').text(localSigns.length)
}

function getParameter(p) {
  let parsedUrl = new URL(window.location.href)
  const code = Number(parsedUrl.searchParams.get(p))
  if (code && code <= 5) {
    return code
  } else if (code > 5) {
    return code % 5
  } else {
    return 1
  }
}

/**
  @param {String} type
  @param {String | Number} value
  @param {Number} index (position of the filter element)
*/
function filterByType(type, value, index = 0) {
  const localSigns = JSON.parse(localStorage.getItem('signs'))
  const user_signs = localSigns.map((name) => {
    if (filterReadySigns[name]) {
      return filterReadySigns[name]
    }
    return null
  })
  console.log(user_signs)
  // signs container
  const signsContainer = document.getElementById('signs')
  // remove all child nodes of signs container
  signsContainer.innerHTML = ''

  // update filters
  // check if filters object has a key (type)
  if (filters[type]) {
    if (!filters[type].includes(value)) {
      filters[type].push(value)
    } else {
      // do nothing
    }
  } else {
    filters[type] = [value]
  }

  // filter signs based on the type (property) and value
  if (type !== 'default') {
    document.getElementById(`${type}-${index}`).style.fontWeight = 'bold'

    results = []
    console.log(filters)
    user_signs.forEach((sign) => {
      if (sign) {
        // when no filter is selected in any column
        if (
          filters['hands'] === undefined ||
          filters['location'] === undefined ||
          filters['Palm Orientation'] === undefined
        ) {
          if (isFilterMatch('hands', sign)) {
            updateResults(sign)
          } else if (isFilterMatch('handshape', sign)) {
            updateResults(sign)
          } else if (isFilterMatch('location', sign)) {
            updateResults(sign)
          } else if (isFilterMatch('Palm Orientation', sign)) {
            updateResults(sign)
          } else if (isFilterMatch('movement', sign)) {
            updateResults(sign)
          }
        } else if (
          isFilterMatch('hands', sign) &&
          isFilterMatch('handshape', sign) &&
          isFilterMatch('location', sign) &&
          isFilterMatch('movement', sign) &&
          isFilterMatch('Palm Orientation', sign)
        ) {
          updateResults(sign)
        }
      }
    })

    console.log(results)
  } else {
    // when filter type is default, show all signs
    results = [...initialSigns]
  }

  const errorMessageEl = document.getElementById('error-message')

  if (results.length === 0) {
    $('.results-grid-container').innerHTML = ''
    $('.results-grid-container').height(0)
    errorMessageEl.style.display = 'flex'
    errorMessageEl.textContent = 'No signs found. Update your filters!'
  } else {
    errorMessageEl.style.display = 'none'

    const stimuliSign = localStorage.getItem('stimuliSign')
    let mainIndex = -1
    let position_sign = {}
    const participantCode = getParameter('p')
    const positionIndex = POSITION_RANGE[participantCode - 1]
    let ui_signs = []

    results.forEach((sign, index) => {
      if (
        sign.name === stimuliSign &&
        STIMULI_SIGNS.includes(stimuliSign.toUpperCase())
      ) {
        mainIndex = index
        if (position_sign[positionIndex - 1]) {
          position_sign[index] = position_sign[positionIndex - 1]
          position_sign[positionIndex - 1] = sign
        } else {
          position_sign[positionIndex - 1] = sign
        }
      } else {
        if (position_sign[index]) {
          position_sign[mainIndex] = sign
        } else {
          position_sign[index] = sign
        }
      }
    })

    ui_signs = Object.values(position_sign)

    console.log(position_sign, ui_signs)

    // loop through the results and create a div with an img element for each sign
    // append the above elements to signs container
    ui_signs.forEach((sign, index) => {
      // const divElement = document.createElement('div')
      // const imgElement = document.createElement('img')
      // const labelElement = document.createElement('p')
      // labelElement.classList.add('result-title')
      // imgElement.classList.add('result-image')
      // imgElement.src = sign.URL
      // imgElement.alt = `${sign.name.toLocaleUpperCase()} Sign Image`
      // imgElement.title = `${sign.name} Sign Image`
      // labelElement.innerText = `${sign.name}`
      // divElement.appendChild(imgElement)
      // divElement.appendChild(labelElement)
      // divElement.classList.add('result-box')
      // signsContainer.appendChild(divElement)
      addSign(sign, index)
    })
  }

  // update the number of signs in the UI
  $('.number-of-signs').text(results.length)
}
